channels:
- conda-forge
dependencies:
- python=3.10.4
- pip<=22.0.2
- pip:
  - mlflow
  - cloudpickle==2.0.0
  - colorama==0.4.4
  - ipywidgets==7.7.0
  - scikit-learn==1.1.0
  - seaborn==0.11.2
  - typing-extensions==4.2.0
name: mlflow-env
