name: model-metrics
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Metrics

        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# Metrics" >> report.md
          echo "# Confusion Matrix" >> report.md
          cml send-comment report.md
